name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test application
      run: echo "Test"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Build Application
      run:
        echo "Build"

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Application
      run:
        echo "Deploy"
